[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nk_datasets"
version = "0.1.0"
description = "NK baseball datasets (NPB, KBO) packaged with pandas loaders + Some MLB data that aligned with NPB and KBO columns and MLB players played either in KBO or NPB"
readme = "README.md"
license = {text = "MIT"}
authors = [{ name = "Myungkeun Park" }]
requires-python = ">=3.9"
dependencies = ["pandas>=1.5"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["nk"]

[tool.setuptools.package-data]
"*" = ["data/*.csv"]