[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mnk_datasets"
version = "0.1.0"
description = "NPB and KBO baseball datasets with pandas loaders, plus aligned MLB data for players who played in KBO or NPB"
readme = "README.md"
license = {text = "MIT"}
authors = [{ name = "Myungkeun Park" }]
requires-python = ">=3.9"
dependencies = ["pandas>=1.5"]

[tool.setuptools.packages.find]
where = ["nk"]

[tool.setuptools.package-data]
"*": ["data/*.csv"]
